# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20191122_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='跟进日期'),
        ),
    ]
