# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-24 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20191123_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='确认日期'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='交款日期'),
        ),
    ]
