# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-24 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20191124_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='交款日期'),
        ),
    ]
