# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20191124_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrecord',
            name='homework',
        ),
    ]
